# ============================================================
# Mac 1 - lobby-service (172.20.10.2)
# Esegui con: docker compose -f docker-compose.lobby.yml up --build
# ============================================================
services:
  lobby-service:
    build:
      context: ./lobby-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=mongodb+srv://danielmeco20_db_user:gszuPhM8DxIAb50B@theimpostor.q4obqb7.mongodb.net/theimpostor?appName=TheImpostor
      - COMM_SERVICE_URL=http://172.20.10.5:3000

